### ISSUE TITLE
misleading message if one line import and no double empty line after import

### ISSUE THREAD

**Issue by jensens** [gforcada/flake8-isort#6] opened 2016-02-08 15:50 UTC
if you have something like:

    # -*- coding: utf-8 -*-
    from pyramid.interfaces import IAuthenticationPolicy

    FOO = 'bar'
    # ...

this leads in 

    ERROR: /home/workspace/my.project/src/my/projectsecurity.py Imports are incorrectly sorted.
    /home/workspace/my.project/src/my/projectsecurity.py:0:1: I001 found unsorted imports

After inserting another blank line after the import its found as ok.

**Comment by gforcada** [comment] 2016-02-08 19:50
True, the problem is that ``isort`` only reports if there are changes between before and after applying isort on the file: https://github.com/gforcada/flake8-isort/blob/master/flake8_isort.py#L38

OTOH just running isort on that file fixes it, so maybe we could rename the error message to say *"please run isort on this file, it needs to be updated"*?

Would that work?

**Comment by gforcada** [comment] 2016-02-16 21:51
Fixed on https://github.com/gforcada/flake8-isort/commit/533fc81135f60ca456a5ee9c3212f2b15adeece6

**Closed by gforcada** 2016-02-16 21:51 UTC
